# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = crifanlib_csharp
SUB_SRC_FILES = \
    preface.xml \
    ch01_treeview_treenode.xml \
    ch02_unit_conversion.xml \
    ch03_values.xml \
    ch04_time.xml \
    ch05_string.xml \
    ch06_array.xml \
    ch07_cookie.xml \
    ch08_serialize_deserialize.xml \
    ch09_http.xml \
    ch010_file_folder.xml \
    ch011_screen.xml \
    ch012_runtime.xml \
    ch013_html_parse.xml \
    ch014_emb_dll_to_exe.xml \
    ch015_datagridview.xml \
    ch016_json.xml \
    reference.xml \

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk